phases:
- phase: Windows_VisualStudio_Integration_Tests
  queue:
    name: dotnet-external-temp-vs2017
    timeoutInMinutes: 90

  steps:
    - script: build/scripts/cibuild.cmd -configuration Debug -testVsi 
      displayName: Build and Test

    - task: PublishTestResults@1
      inputs:
        testRunner: XUnit
        testResultsFiles: '**/xUnitResults/*.xml'
        mergeTestResults: true
        testRunTitle: 'Windows Visual Studio Integration Debug' 
      condition: succeededOrFailed()

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\Binaries\$(_configuration)\Logs'
        ArtifactName: 'Windows Visual Studio Integration Debug'
        publishLocation: Container
      continueOnError: true
      condition: failed()

