phases:
- phase: Windows_VisualStudio_Integration_Tests
  queue:
    name: dotnet-external-temp-vs2017
    timeoutInMinutes: 70

  steps:
    - script: build/scripts/cibuild.cmd -configuration Release -testVsi 
      displayName: Build and Test

    - task: PublishTestResults@1
      inputs:
        testRunner: XUnit
        testResultsFiles: '**/xUnitResults/*.xml'
        mergeTestResults: true
        testRunTitle: 'Windows Visual Studio Integration Debug' 
      condition: always()

    - task: PublishBuildArtifacts@1
      displayName: Publish Logs
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\Binaries\Release\Logs'
        ArtifactName: 'Windows Visual Studio Integration Debug'
        publishLocation: Container
      continueOnError: true
      condition: or(failed(), canceled())

    - task: PublishBuildArtifacts@1
      displayName: Publish Screenshots
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\Binaries/Release/UnitTests/Microsoft.VisualStudio.LanguageServices.IntegrationTests/xUnitResults/'
        ArtifactName: 'Screenshots' 
        publishLocation: Container
      continueOnError: true
      condition: or(failed(), canceled())
