# Disable CI triggers
trigger: none
pr: none

# Nightly run of integration tests against the scouting queue
schedules:
- cron: "0 0 * * *"
displayName: Daily midnight build
branches:
    include:
    - main
    - main-vs-deps

variables:
- name: queueName
  value: windows.vs2022preview.scout.amd64.open

stages:
- stage: Debug_Integration
  dependsOn: []
  jobs:
  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    - job: VS_Integration_Debug_32
      pool:
        name: NetCore-Public
        demands: ImageOverride -equals $(queueName)
      timeoutInMinutes: 150
      variables:
        - name: XUNIT_LOGS
          value: $(Build.SourcesDirectory)\artifacts\log\Debug
      steps:
        - template: eng/pipelines/test-integration-job.yml
          parameters:
            configuration: Debug
            oop64bit: false
            lspEditor: false

  - job: VS_Integration_Debug_64
    pool:
      name: NetCore-Public
      demands: ImageOverride -equals $(queueName)
    timeoutInMinutes: 150
    variables:
      - name: XUNIT_LOGS
        value: $(Build.SourcesDirectory)\artifacts\log\Debug
    steps:
      - template: eng/pipelines/test-integration-job.yml
        parameters:
          configuration: Debug
          oop64bit: true
          lspEditor: false

- stage: Release_Integration
  dependsOn: []
  jobs:
  - job: VS_Integration_Release_32
    pool:
      name: NetCore-Public
      demands: ImageOverride -equals $(queueName)
    timeoutInMinutes: 150
    variables:
      - name: XUNIT_LOGS
        value: $(Build.SourcesDirectory)\artifacts\log\Release
    steps:
      - template: eng/pipelines/test-integration-job.yml
        parameters:
          configuration: Release
          oop64bit: false
          lspEditor: false

  - ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    - job: VS_Integration_Release_64
      pool:
        name: NetCore-Public
        demands: ImageOverride -equals $(queueName)
      timeoutInMinutes: 150
      variables:
        - name: XUNIT_LOGS
          value: $(Build.SourcesDirectory)\artifacts\log\Release
      steps:
        - template: eng/pipelines/test-integration-job.yml
          parameters:
            configuration: Release
            oop64bit: true
            lspEditor: false
